name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou a branch que você estiver usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # ou a versão que você estiver usando

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "amarildotardivo@gmail.com"
          git config --global user.name "Amarildo Tardivo"

      - name: Deploy to GitHub Pages
        run: |
          npm install gh-pages --save-dev    # Certifique-se de que gh-pages está instalado
          npm run build                      # Execute a construção do projeto, se necessário
          npx gh-pages -d build              # Use npx para executar o gh-pages
